FROM 240247221724.dkr.ecr.eu-west-1.amazonaws.com/nginx_noheader:1.19.2-brotli

ENV TZ Africa/Johannesburg

RUN apk update && apk upgrade --no-cache

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf
